load:
  description: 加载网页链接
  fields:
    url:
      name: 网页链接地址
      description: 网页链接地址
      example: 'https://ha.jiluxinqing.com'
      selector:
        text:
    ip:
      name: IP地址 
      description: 小米平板IP地址
      example: '192.168.1.111'
      selector:
        text: